server:
  port: 8082

gpayments:
  asAuthUrl: https://api.as.testlab.3dsecure.cloud:7443
  baseUrl: http://localhost:8082
  #certFileName: <Full file name and path of the client certificate>
  #certFileName: .p12
  certFileName: .p12
  #certFilePassword: <The password for the client certificate>
  certFilePassword:
  groupAuth: false
  merchantToken: # Your merchantToken when groupAuth = true

